### ISSUE TITLE
Review page showing error

### ISSUE THREAD

**Issue by swapnilkadakia** [roarceus/book_reviews#1]
When I click on the book to see the reviews, it shows,
 Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by roarceus** [comment]
> When I click on the book to see the reviews, it shows,
> Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This is happening because the application is connected to Goodreads API and from December 2020 they have removed developer APIs. Because of this, the book review app is not able to receive the data and parse it. I will try to fix it with some other service if possible.
